### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by yan12125** [yan12125/google-play-downloader#2]
Google has removed ClientLogin interface, which is used in this tool. As a result, any download will give 404:
(See https://developers.google.com/identity/protocols/AuthForInstalledApps)

```
$ ./gplay-downloader.py -f config.json -n jp.naver.line.android

    GooglePlay Downloader - Directly download apks from GooglePlay to your PC.
    Copyleft Simone Margaritelli <evilsocket@evilsocket.net>
    http://www.evilsocket.net


@ Logging in ...
Traceback (most recent call last):
  File "./gplay-downloader.py", line 120, in <module>
    main()
  File "./gplay-downloader.py", line 104, in main
    market.login()
  File "/home/yen/Computer/Programming/python/google-play-downloader/Market.py", line 32, in login
    data = self._request(self.LOGIN_PAGE, params)
  File "/home/yen/Computer/Programming/python/google-play-downloader/Market.py", line 20, in _request
    connection = self._opener.open(url, encoded_params.encode('utf-8'))
  File "/usr/lib/python3.4/urllib/request.py", line 469, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 507, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 587, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

I'll try to integrate OAuth 2.0 as soon as possible.

**Comment by yan12125** [comment]
Fixed in 2a68ad07da8242459282ad12214e2e08d4c840bd
